// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package chief is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	NewKeyRequest
	NewKeyResponse
*/
package chief

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewKeyResponse_ErrorCode int32

const (
	NewKeyResponse_OK       NewKeyResponse_ErrorCode = 0
	NewKeyResponse_DRAINED  NewKeyResponse_ErrorCode = 2
	NewKeyResponse_INTERNAL NewKeyResponse_ErrorCode = -1
)

var NewKeyResponse_ErrorCode_name = map[int32]string{
	0:  "OK",
	2:  "DRAINED",
	-1: "INTERNAL",
}
var NewKeyResponse_ErrorCode_value = map[string]int32{
	"OK":       0,
	"DRAINED":  2,
	"INTERNAL": -1,
}

func (x NewKeyResponse_ErrorCode) String() string {
	return proto.EnumName(NewKeyResponse_ErrorCode_name, int32(x))
}
func (NewKeyResponse_ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type NewKeyRequest struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *NewKeyRequest) Reset()                    { *m = NewKeyRequest{} }
func (m *NewKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*NewKeyRequest) ProtoMessage()               {}
func (*NewKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewKeyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NewKeyResponse struct {
	Code  NewKeyResponse_ErrorCode `protobuf:"varint,1,opt,name=Code,enum=chief.NewKeyResponse_ErrorCode" json:"Code,omitempty"`
	Name  string                   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Value uint64                   `protobuf:"varint,3,opt,name=Value" json:"Value,omitempty"`
}

func (m *NewKeyResponse) Reset()                    { *m = NewKeyResponse{} }
func (m *NewKeyResponse) String() string            { return proto.CompactTextString(m) }
func (*NewKeyResponse) ProtoMessage()               {}
func (*NewKeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewKeyResponse) GetCode() NewKeyResponse_ErrorCode {
	if m != nil {
		return m.Code
	}
	return NewKeyResponse_OK
}

func (m *NewKeyResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewKeyResponse) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*NewKeyRequest)(nil), "chief.NewKeyRequest")
	proto.RegisterType((*NewKeyResponse)(nil), "chief.NewKeyResponse")
	proto.RegisterEnum("chief.NewKeyResponse_ErrorCode", NewKeyResponse_ErrorCode_name, NewKeyResponse_ErrorCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chief service

type ChiefClient interface {
	NewKey(ctx context.Context, in *NewKeyRequest, opts ...grpc.CallOption) (*NewKeyResponse, error)
}

type chiefClient struct {
	cc *grpc.ClientConn
}

func NewChiefClient(cc *grpc.ClientConn) ChiefClient {
	return &chiefClient{cc}
}

func (c *chiefClient) NewKey(ctx context.Context, in *NewKeyRequest, opts ...grpc.CallOption) (*NewKeyResponse, error) {
	out := new(NewKeyResponse)
	err := grpc.Invoke(ctx, "/chief.Chief/NewKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Chief service

type ChiefServer interface {
	NewKey(context.Context, *NewKeyRequest) (*NewKeyResponse, error)
}

func RegisterChiefServer(s *grpc.Server, srv ChiefServer) {
	s.RegisterService(&_Chief_serviceDesc, srv)
}

func _Chief_NewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChiefServer).NewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chief.Chief/NewKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChiefServer).NewKey(ctx, req.(*NewKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chief_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chief.Chief",
	HandlerType: (*ChiefServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewKey",
			Handler:    _Chief_NewKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0xce, 0xc8, 0x4c, 0x4d, 0x53, 0x52,
	0xe6, 0xe2, 0xf5, 0x4b, 0x2d, 0xf7, 0x4e, 0xad, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x12, 0xe2, 0x62, 0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3,
	0x95, 0x56, 0x30, 0x72, 0xf1, 0xc1, 0x54, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x19, 0x73,
	0xb1, 0x38, 0xe7, 0xa7, 0x40, 0x94, 0xf1, 0x19, 0xc9, 0xeb, 0x81, 0x4d, 0xd3, 0x43, 0x55, 0xa4,
	0xe7, 0x5a, 0x54, 0x94, 0x5f, 0x04, 0x52, 0x16, 0x04, 0x56, 0x0c, 0x37, 0x9b, 0x09, 0x61, 0xb6,
	0x90, 0x08, 0x17, 0x6b, 0x58, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x4b, 0x10,
	0x84, 0xa3, 0x64, 0xce, 0xc5, 0x09, 0xd7, 0x2c, 0xc4, 0xc6, 0xc5, 0xe4, 0xef, 0x2d, 0xc0, 0x20,
	0xc4, 0xcd, 0xc5, 0xee, 0x12, 0xe4, 0xe8, 0xe9, 0xe7, 0xea, 0x22, 0xc0, 0x24, 0x24, 0xca, 0xc5,
	0xe1, 0xe9, 0x17, 0xe2, 0x1a, 0xe4, 0xe7, 0xe8, 0x23, 0xf0, 0x1f, 0x06, 0x18, 0x8d, 0xec, 0xb8,
	0x58, 0x9d, 0x41, 0x4e, 0x11, 0x32, 0xe5, 0x62, 0x83, 0xb8, 0x46, 0x48, 0x04, 0xcd, 0x71, 0x60,
	0x7f, 0x4a, 0x89, 0x62, 0x75, 0x72, 0x12, 0x1b, 0x38, 0x74, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x03, 0xaa, 0x05, 0xc5, 0x2c, 0x01, 0x00, 0x00,
}
